//FETCH ALL ACTIONTYPE
export const LOAD_SCHEDULES_START = "LOAD_SCHEDULES_START"
export const LOAD_SCHEDULES_SUCCESS = "LOAD_SCHEDULES_SUCCESS"
export const LOAD_SCHEDULES_FAIL = "LOAD_SCHEDULES_FAIL"


//FILTER ACTIONTYPE
export const FILTER_SCHEDULES_START = "FILTER_SCHEDULES_START"
export const FILTER_SCHEDULES_SUCCESS = "FILTER_SCHEDULES_SUCCESS"
export const FILTER_SCHEDULES_FAIL = "FILTER_SCHEDULES_FAIL"

//CREATE ACTIONTYPE
export const CREATE_SCHEDULE_START = "CREATE_SCHEDULE_START"
export const CREATE_SCHEDULE_SUCCESS = "CREATE_SCHEDULE_SUCCESS"
export const CREATE_SCHEDULE_FAIL = "CREATE_SCHEDULE_FAIL"

//FETCH BY ID ACTION TYPE
export const FIND_SCHEDULEBYID_START = "FIND_SCHEDULEBYID_START"
export const FIND_SCHEDULEBYID_SUCCESS = "FIND_SCHEDULEBYID_SUCCESS"
export const FIND_SCHEDULEBYID_FAIL = "FIND_SCHEDULEBYID_FAIL"

//UPDATE ACTION TYPE
export const UPDATE_SCHEDULE_START = "UPDATE_SCHEDULE_START"
export const UPDATE_SCHEDULE_SUCCESS = "UPDATE_SCHEDULE_SUCCESS"
export const UPDATE_SCHEDULE_FAIL = "UPDATE_SCHEDULE_FAIL"


// delete action type
export const DELETE_SCHEDULE_START = "DELETE_SCHEDULE_START"
export const DELETE_SCHEDULE_SUCCESS = "DELETE_SCHEDULE_SUCCESS"
export const DELETE_SCHEDULE_FAIL = "DELETE_SCHEDULE_FAIL"